"""add google_id and make password nullable

Revision ID: 6c7878a3a56e
Revises: ab231eed4765
Create Date: 2026-05-03 17:08:27.760696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c7878a3a56e'
down_revision = 'ab231eed4765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('password',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
