"""add forgot_password_token to user table

Revision ID: ab231eed4765
Revises: dce6366014ee
Create Date: 2026-04-25 18:16:16.456596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab231eed4765'
down_revision = 'dce6366014ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forgot_password_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('forgot_password_token')
    # ### end Alembic commands ###
