"""rounds table - add created_at column

Revision ID: dce6366014ee
Revises: 2e26f77645d1
Create Date: 2024-02-06 05:51:13.530998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dce6366014ee'
down_revision = '2e26f77645d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
