"""user column changes

Revision ID: ed0050cbff45
Revises: be70026b0cc8
Create Date: 2024-02-02 06:16:52.682973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed0050cbff45'
down_revision = 'be70026b0cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###
